name: TownyShow
version: '1.0.0'
main: com.r1lit.spigot.TownyShow
api-version: '1.20'
load: POSTWORLD
commands:
  tshow:
    description: TownyShow
    usage: /tshow reload
    permission: townyshow.admin
depend:
  - Towny
softdepend:
  - PlaceholderAPI